### ISSUE TITLE
Query to generation per plant does not work

### ISSUE THREAD

**Issue by huertamir** [EnergieID/entsoe-py#130]
Other queries work but when calling to the query to generation per plant the system hangs.

**Comment by fboerman** [comment]
hi @huertamir could you please provide a code sample?

**Comment by aliciabassiere** [comment]
I have the same issue, also for DK.

I think the problem comes from the fact that the query seems to use control_area instead of a bidding zone.

HTTPError                                 Traceback (most recent call last)

~\miniconda3\lib\site-packages\entsoe\entsoe.py in _base_request(self, params, start, end)
     92         try:
---> 93             response.raise_for_status()
     94         except requests.HTTPError as e:

~\miniconda3\lib\site-packages\requests\models.py in raise_for_status(self)
    942         if http_error_msg:
--> 943             raise HTTPError(http_error_msg, response=self)
    944 

HTTPError: 400 Client Error: Bad Request for url: https://transparency.entsoe.eu/api?documentType=A73&processType=A16&in_Domain=10Y1001A1001A83F&securityToken="TOKEN"&periodStart=201412312300&periodEnd=201501012300

**Comment by fboerman** [comment]
hi @fedeguerr  fine that you react to old post if it has new info! this is very puzzling indeed. so you are saying that even with control_area you cant get it to work?

**Comment by blacksocket** [comment]
Hello All,

I am having the same issue below when calling documentType=A73&processType=A16&in_Domain=10YPL-AREA-----S&psrType=B16. The data are indeed visible on entsoe webpage. Also the same query for different psrType works properly like i.e. B02.


2022-10-01 00:00:00+02:00
B16
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/entsoe/entsoe.py", line 93, in _base_request
    response.raise_for_status()
  File "/usr/local/lib/python3.7/dist-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://transparency.entsoe.eu/api?documentType=A73&processType=A16&in_Domain=10YPL-AREA-----S&psrType=B16&securityToken=d059c8b6-b0c4-4462-8d03-89ec15557100&periodStart=202209302200&periodEnd=202210012200

**Comment by echoqsun** [comment]
Hello All,

I had an issue when I query data client.query_generation_per_plant('UA_BEI', start=start, end=end, nett=True, include_eic=True),
It raised this kind of error, and it seems from the parse error![image](https://github.com/EnergieID/entsoe-py/assets/92441765/2ef721eb-479b-4164-9bc0-0afb1c87fc6f), But ENTSOE-PT has this data.
![image](https://github.com/EnergieID/entsoe-py/assets/92441765/ae2a08a1-d9a6-43c3-a831-2dda70e9c2c8)

How can we figure out this issue?

**Comment by fboerman** [comment]
hi @blacksocket I am not very well versed in those business parameters. Could you explain to me the difference of what call works and what doesnt? also do not post your api key please.

hi @echoqsun the crash only shows up for include_eic=True.  I am trying to get to the bottom of it but havent found the bug yet. will update you when I do

**Comment by sereksim** [comment]
For me the query does not work either. It is not possible to get the data for Germany (DE_LU or DE_AT_LU)
```python
start = pd.Timestamp('20201201', tz='Europe/Brussels')
end = pd.Timestamp('20201202', tz='Europe/Brussels')
client.query_generation_per_plant('DE_LU', start=start, end=end,psr_type=None, include_eic=False)
```
throws an InvalidBusinessParameterError:
<details>
<summary>Traceback</summary>

```shell
Traceback (most recent call last):
  File "C:\Users\...\miniconda3\lib\site-packages\entsoe\entsoe.py", line 98, in _base_request
    response.raise_for_status()
  File "C:\Users\...\miniconda3\lib\site-packages\requests\models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://web-api.tp.entsoe.eu/api?documentType=A73&processType=A16&in_Domain=10Y1001A1001A82H&securityToken=...&periodStart=202011302300&periodEnd=202012012300

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\...\miniconda3\lib\site-packages\entsoe\decorators.py", line 125, in day_wrapper
    frame = func(*args, start=_start, end=_end, **kwargs)
  File "C:\Users\...\miniconda3\lib\site-packages\entsoe\entsoe.py", line 1952, in query_generation_per_plant
    text = super(EntsoePandasClient, self).query_generation_per_plant(
  File "C:\Users\...\miniconda3\lib\site-packages\entsoe\entsoe.py", line 367, in query_generation_per_plant
    response = self._base_request(params=params, start=start, end=end)
  File "C:\Users\...\miniconda3\lib\site-packages\entsoe\decorators.py", line 22, in retry_wrapper
    result = func(*args, **kwargs)
  File "C:\Users\...\miniconda3\lib\site-packages\entsoe\entsoe.py", line 107, in _base_request
    raise InvalidBusinessParameterError
entsoe.exceptions.InvalidBusinessParameterError
Breakpoint reached: Any exception
Stack: 
	_base_request, entsoe.py:107
	retry_wrapper, decorators.py:22
	query_generation_per_plant, entsoe.py:367
	query_generation_per_plant, entsoe.py:1952
	day_wrapper, decorators.py:125
	<module>, entsoe_api.py:22
python-BaseException
```

</details> 


```python
start = pd.Timestamp('20161215', tz='Europe/Brussels')
end = pd.Timestamp('20161216', tz='Europe/Brussels')
client.query_generation_per_plant('DE_AT_LU', start=start, end=end, psr_type=None, include_eic=False)
```
throws the same:
<details><summary>Stacktrace</summary>
<p>

```shell
Traceback (most recent call last):
  File "C:\Users\...\miniconda3\lib\site-packages\entsoe\entsoe.py", line 98, in _base_request
    response.raise_for_status()
  File "C:\Users\...\miniconda3\lib\site-packages\requests\models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://web-api.tp.entsoe.eu/api?documentType=A73&processType=A16&in_Domain=10Y1001A1001A63L&securityToken=...&periodStart=201612142300&periodEnd=201612152300

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\...\miniconda3\lib\site-packages\entsoe\decorators.py", line 125, in day_wrapper
    frame = func(*args, start=_start, end=_end, **kwargs)
  File "C:\Users\...\miniconda3\lib\site-packages\entsoe\entsoe.py", line 1952, in query_generation_per_plant
    text = super(EntsoePandasClient, self).query_generation_per_plant(
  File "C:\Users\...\miniconda3\lib\site-packages\entsoe\entsoe.py", line 367, in query_generation_per_plant
    response = self._base_request(params=params, start=start, end=end)
  File "C:\Users\...\miniconda3\lib\site-packages\entsoe\decorators.py", line 22, in retry_wrapper
    result = func(*args, **kwargs)
  File "C:\Users\...\miniconda3\lib\site-packages\entsoe\entsoe.py", line 107, in _base_request
    raise InvalidBusinessParameterError
entsoe.exceptions.InvalidBusinessParameterError
Breakpoint reached: Any exception
Stack: 
	_base_request, entsoe.py:107
	retry_wrapper, decorators.py:22
	query_generation_per_plant, entsoe.py:367
	query_generation_per_plant, entsoe.py:1952
	day_wrapper, decorators.py:125
	<module>, entsoe_api.py:25
python-BaseException
```

</p>
</details> 

---

On the other hand, e.g. AT (Austria) works without problems:
```python
start = pd.Timestamp('20201201', tz='Europe/Brussels')
end = pd.Timestamp('20210101', tz='Europe/Brussels')
client.query_generation_per_plant('AT', start=start, end=end, psr_type=None, include_eic=False)
```

**Comment by sereksim** [comment]
@fboerman 
> the crash only shows up for include_eic=True

As you can see in the code i posted above, the error appears with include_eic=False too

**Comment by Bert-Herteleer** [comment]
From [electricitymaps/ENTSOE.py](https://github.com/electricitymaps/electricitymaps-contrib/blob/master/parsers/ENTSOE.py) the comment states that generation per unit is only at EIC level:

> # Generation per unit can only be obtained at EIC (Control Area) level

The list of EICs can be found at: [ENTSO-E transparency API](https://transparency.entsoe.eu/content/static_content/Static%20content/web%20api/Guide.html#_areas) or look at `ENTSOE_DOMAIN_MAPPINGS` in the Electricity Maps file.

See also the [Postman API documentation])https://documenter.getpostman.com/view/7009892/2s93JtP3F6#537e921c-b261-46d1-9515-32958e8f520a), which also indicates that the EIC code must be used. In some cases, this means that the "easy" country code must be replaced by the more involved EIC code. For the example of Belgium:
`country_code = 'BE'` does not work, whereas `EIC_code = '10YBE----------2'` used as `client.query_generation(EIC_code,start=start, end=end)` works.

**Comment by MuhammadPathan** [comment]
Any updates on this? tried the latest version and generation per plant still causing issue


the InvalidBusinessParameterError:  still happening for Germany 



tried different country (BE) and code works fine 

Code working fine 

```
from entsoe import EntsoePandasClient
import pandas as pd
from datetime import datetime, timedelta

# Initialize the client with API key
client = EntsoePandasClient(api_key='my_key')
start = pd.Timestamp('20171201', tz='Europe/Brussels')
end = pd.Timestamp('20180101', tz='Europe/Brussels')
country_code = 'BE'

df=client.query_generation_per_plant(country_code, start=start, end=end, psr_type=None, include_eic=False)

```


Code causing issues 

```
from entsoe import EntsoePandasClient
import pandas as pd
from datetime import datetime, timedelta


# Initialize the client with your API key
client = EntsoePandasClient(api_key='49a6a44d-268c-4ea3-89ee-37a1625155ed')
start = pd.Timestamp('20171201', tz='Europe/Brussels')
end = pd.Timestamp('20180101', tz='Europe/Brussels')
country_code = 'DE_AT_LU'



df=client.query_generation_per_plant(country_code, start=start, end=end, psr_type=None, include_eic=False)

```

Things tried 

trying all country country_code for Germany alternatives such as DE_AT_LU, DE,DE_LU that did not work 

tried using EIC_code instead still getting same issue

**Comment by jenshoej** [comment]
I encounter the same issue. It may seem it is at the ENTSO-E level. When using 'DK', 'DK_1' 'DK_2' or their EIC as the country_code, I get the error:

InvalidBusinessParameterError

HTTPError: 400 Client Error: Bad Request for url: https://web-api.tp.entsoe.eu/api?documentType=A73&processType=A16&in_Domain=10YDK-1--------W&securityToken=MY_TOKEN&periodStart=202211302300&periodEnd=202212012300

(I removed my token)

In the above url, the in_Domain is the DK_1 EIC. Pasting this url a browser or curling this in a terminal opens an xml entso-e web api page with this message:

"Invalid business dimension parameters provided. Please check you request against dependency tables. One of the following parameters is not valid for Actual Generation Output per Generation Unit [16.1.A]: 10YDK-1--------W"

When changing the in_Domain to 10YBE----------2, the EIC for Belgium in the url for instance, it returns proper xml data without any error messages.

So there seems to be a problem at the ENTSO-E level between the in_Domain and the control area/EIC codes of some countries like Denmark and Germany. 

I tried with Sweden which has several bidding zones and that works too.

I have opened a ticket with ENTSO-E for this issue.
