### ISSUE TITLE
Example not working 

### ISSUE THREAD

**Issue by hardcodedpassword** [EnergieID/entsoe-py#199]
Hi,

When executing the example given for day-ahead prices using PandasClient:

```
from entsoe import EntsoePandasClient
import pandas as pd

client = EntsoePandasClient(api_key='xxxxxxxxxx')

start = pd.Timestamp('20171201', tz='Europe/Brussels')
end = pd.Timestamp('20180101', tz='Europe/Brussels')
country_code = 'BE'  # Belgium
country_code_from = 'FR'  # France
country_code_to = 'DE_LU' # Germany-Luxembourg
type_marketagreement_type = 'A01'
contract_marketagreement_type = "A01"

# methods that return Pandas Series
ts=client.query_day_ahead_prices(country_code, start=start,end=end)
```

client.query_day_ahead_prices() yields the following exception:

```
/Users/macmini/code/dayAhead/venv/bin/python "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/pydevd.py" --multiproc --qt-support=auto --client 127.0.0.1 --port 52590 --file /Users/macmini/code/dayAhead/main.py
Connected to pydev debugger (build 203.6682.179)
/Users/macmini/code/dayAhead/venv/lib/python3.6/site-packages/bs4/builder/__init__.py:546: XMLParsedAsHTMLWarning: It looks like you're parsing an XML document using an HTML parser. If this really is an HTML document (maybe it's XHTML?), you can ignore or filter this warning. If it's XML, you should know that using an XML parser will be more reliable. To parse this document as XML, make sure you have the lxml package installed, and pass the keyword argument `features="xml"` into the BeautifulSoup constructor.
  XMLParsedAsHTMLWarning.MESSAGE, XMLParsedAsHTMLWarning
Traceback (most recent call last):
  File "/Users/macmini/code/dayAhead/venv/lib/python3.6/site-packages/entsoe/decorators.py", line 90, in year_wrapper
    frame = func(*args, start=_start, end=_end, **kwargs)
  File "/Users/macmini/code/dayAhead/venv/lib/python3.6/site-packages/entsoe/entsoe.py", line 972, in query_day_ahead_prices
    series = parse_prices(text)
  File "/Users/macmini/code/dayAhead/venv/lib/python3.6/site-packages/entsoe/parsers.py", line 44, in parse_prices
    series.append(_parse_price_timeseries(soup))
  File "/Users/macmini/code/dayAhead/venv/lib/python3.6/site-packages/entsoe/parsers.py", line 489, in _parse_price_timeseries
    series.index = _parse_datetimeindex(soup)
  File "/Users/macmini/code/dayAhead/venv/lib/python3.6/site-packages/entsoe/parsers.py", line 635, in _parse_datetimeindex
    index = pd.date_range(start=start, end=end, freq=delta, inclusive='left')
  File "/Users/macmini/code/dayAhead/venv/lib/python3.6/site-packages/pandas/core/indexes/datetimes.py", line 1007, in date_range
    **kwargs,
TypeError: _generate_range() got an unexpected keyword argument 'inclusive'
python-BaseException

Process finished with exit code 1
```

Debugging shows that an XML response has been received.
Note that the Raw Client equivalent example works good.
Could it be related to [issue 198](https://github.com/EnergieID/entsoe-py/issues/198)?

**Comment by jdtrebbien** [comment]
Your example is working for me. What version are you using? I tried with version 0.5.4, where I only got a `XMLParsedAsHTMLWarning`. If you also want to get rid of the warning try getting version 0.5.5 (which is not released yet) by doing `pip install git+https://github.com/EnergieID/entsoe-py.git`.

**Comment by hardcodedpassword** [comment]
My mistake, I was using an old python interpreter which prohibited using the most recent entsoe-py and pandas. I updated the python interpreter, created a new venv and it is working like a charm now.

Thanks!
