### ISSUE TITLE
Exception: Please specify the start and end date explicity with start=<date> when calling this function

### ISSUE THREAD

**Issue by timebis** [EnergieID/entsoe-py#207]
Hi,
I'm trying to use the following example line code : 
from entsoe import EntsoePandasClient
```
import pandas as pd

client = EntsoePandasClient(api_key="MY KEY")

start = pd.Timestamp('20181201', tz='Europe/Brussels')
end = pd.Timestamp('20181202', tz='Europe/Brussels')
country_code = 'BE'  # Belgium
country_code_from = 'FR'  # France
country_code_to = 'DE_LU' # Germany-Luxembourg
type_marketagreement_type = 'A01'
contract_marketagreement_type = "A01"
process_type = "A52"

print(start)
print(end)

res = client.query_procured_balancing_capacity(country_code, start, end, process_type, type_marketagreement_type=None)
```

But i got this error in return  : 

> /home/thomas/PycharmProjects/test_energieID_ENTSO_API/venv/bin/python /snap/pycharm-community/296/plugins/python-ce/helpers/pydev/pydevd.py --cmd-line --multiprocess --qt-support=auto --client 127.0.0.1 --port 39251 --file /home/thomas/PycharmProjects/test_energieID_ENTSO_API/EntsoePandasClient.py 
> 2018-12-01 00:00:00+01:00
> 2018-12-02 00:00:00+01:00
> Traceback (most recent call last):
>   File "/snap/pycharm-community/296/plugins/python-ce/helpers/pydev/pydevd.py", line 1496, in _exec
>     pydev_imports.execfile(file, globals, locals)  # execute the script
>   File "/snap/pycharm-community/296/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
>     exec(compile(contents+"\n", file, 'exec'), glob, loc)
>   File "/home/thomas/PycharmProjects/test_energieID_ENTSO_API/EntsoePandasClient.py", line 49, in <module>
>     res = client.query_procured_balancing_capacity(country_code, start, end, process_type, type_marketagreement_type=None)
>   File "/home/thomas/.local/lib/python3.10/site-packages/entsoe/decorators.py", line 87, in year_wrapper
>     raise Exception('Please specify the start and end date explicity with start=<date> when calling this '
> Exception: Please specify the start and end date explicity with start=<date> when calling this function
> 
> Process finished with exit code 1

Indeed, with a breakpoint in the year_wraper function, we can see that start and end are None. But I don't know why..
![image](https://user-images.githubusercontent.com/48658392/187619907-b6071236-688a-428c-9cf2-0407086de0e3.png)

Does sb have an idea where does it come from ?

**Comment by jdtrebbien** [comment]
`start` and `end` need to be given as kwargs. Just change the function call to `res = client.query_procured_balancing_capacity(country_code, process_type, start=start, end=end, type_marketagreement_type=None)` and it should work.
Note that you also need to change the position of `process_type`.

**Comment by timebis** [comment]
> `start` and `end` need to be given as kwargs. Just change the function call to `res = client.query_procured_balancing_capacity(country_code, process_type, start=start, end=end, type_marketagreement_type=None)` and it should work. Note that you also need to change the position of `process_type`.

Thanks ! It works.

I will try to change the [ReadMe](https://github.com/timebis/entsoe-py/blob/master/README.md).

**Comment by jdtrebbien** [comment]
You don't need to do that. I already had a fixed version ready but hadnt done a PR until now.
