### ISSUE TITLE
Can not acces EntsoE data site anymore since 15.12.2022

### ISSUE THREAD

**Issue by kasol62** [EnergieID/entsoe-py#227]
Connection Error, retrying in 0 seconds
Traceback (most recent call last):
  File "C:\Python\Python311\Lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Python311\Lib\site-packages\urllib3\util\connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Python311\Lib\socket.py", line 961, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "C:\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "C:\Python\Python311\Lib\site-packages\urllib3\connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
                       ^^^^^^^^^^^^^^^^
  File "C:\Python\Python311\Lib\site-packages\urllib3\connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x0000015670523510>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python\Python311\Lib\site-packages\requests\adapters.py", line 489, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "C:\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "C:\Python\Python311\Lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='web-api.tp.entsoe.eu', port=443): Max retries exceeded with url: /api?documentType=A44&in_Domain=10YFI-1--------U&out_Domain=10YFI-1--------U&securityToken=39001d8c-e455-4f53-a3cd-c1316561c256&periodStart=202212172200&periodEnd=202212172200 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000015670523510>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
...etc

**Comment by Relouse** [comment]
I have the same problem! I will write today in support of entsoe

**Comment by matteodefelice** [comment]
Same problem here this morning, yesterday evening everything was ok...

**Comment by fboerman** [comment]
Yes I see the same issue here :(

Met vriendelijke groeten Ir. Frank Boerman https://boerman.dev/

Sent from Proton Mail mobile

-------- Original Message --------

**Comment by RubenVanEldik** [comment]
I get the same error as well. For your information, I think the error first appeared last night around 00:30GMT.

**Comment by JaccoR** [comment]
As an interim solution I switched to https://transparency.entsoe.eu/api which seems to work. But web-api.tp.entsoe.eu seems to resolve again.

**Comment by fboerman** [comment]
it seems this issue has been resolved by transparancy themselves
