### ISSUE TITLE
query_generation and ENTSO-E point NoneType

### ISSUE THREAD

**Issue by ThomasAuriel** [EnergieID/entsoe-py#23]
Hi

On large request, I got an error:

The code:
```python
country = 'DE'
start = pd.Timestamp('2018-01-01 00:00:00', tz='Europe/Brussels')
end = pd.Timestamp('2018-12-31 12:00:00', tz='Europe/Brussels')

result = client.query_generation(country, start=start, end=end, psr_type=None)
```
The log:
```
Traceback (most recent call last):
  File "./project/test.py", line 23, in <module>
    data = ENTSOE.getData(countries, start, end)
  File "./project/entsoe/ENTSOE.py", line 72, in getData
    result = client.query_generation(country, start=start, end=end, psr_type=None)
  File "./project/entsoe/entsoe.py", line 537, in year_wrapper
    in blocks]
  File "./project/entsoe/entsoe.py", line 536, in <listcomp>
    frames = [func(*args, start=_start, end=_end, **kwargs) for _start, _end
  File "./project/entsoe/entsoe.py", line 665, in query_generation
    df = parse_generation(text)
  File "./project/entsoe/parsers.py", line 71, in parse_generation
    ts = _parse_generation_forecast_timeseries(soup)
  File "./project/entsoe/parsers.py", line 247, in _parse_generation_forecast_timeseries
    quantities.append(float(point.find('quantity').text))
AttributeError: 'NoneType' object has no attribute 'text'
```

I imagine that the line `quantities.append(float(point.find('quantity').text))` does not check if the quantity exist ? It feels like ENTSO-E is providing the uncorrect formated data.

**Comment by JrtPec** [comment]
Hi tried replicating your error with your code, but my result came out correct.

My guess is that, due to the request being so big, the API _may_ have a hiccup of sorts and returns faulty data.
Can you do some debugging and see what _is_ in the point object?

I have added more verbose error logging in version 0.2.7 (see 34c2dd74ce8d74a68ca538485d3de2ae4092c377). So when the error pops up again, it might give us some more info.

**Comment by JrtPec** [comment]
One year without follow up - closing
