### ISSUE TITLE
Length mismatch: Expected axis has 24 elements, new values have 1 elements

### ISSUE THREAD

**Issue by fleimgruber** [EnergieID/entsoe-py#71]
Running:

```python
from entsoe import EntsoePandasClient
import pandas as pd

client = EntsoePandasClient(api_key=api_key)

tz = "Europe/Dublin"

start = pd.Timestamp("20180101", tz=tz)
end = pd.Timestamp("20201015", tz=tz)

country_code = "IE-SEM"

df = client.query_day_ahead_prices(country_code, start=start, end=end)
```

fails with

```
Traceback (most recent call last):
  File "C:/Users/user/dev/entsoe-py/scripts/dayahead.py", line 16, in <module>
    df = client.query_day_ahead_prices(country_code, start=start, end=end)
  File "C:\Users\user\dev\entsoe-py\entsoe\entsoe.py", line 740, in year_wrapper
    frame = func(*args, start=_start, end=_end, **kwargs)
  File "C:\Users\user\dev\entsoe-py\entsoe\entsoe.py", line 798, in query_day_ahead_prices
    series = parse_prices(text)
  File "C:\Users\user\dev\entsoe-py\entsoe\parsers.py", line 39, in parse_prices
    series = series.append(_parse_price_timeseries(soup))
  File "C:\Users\user\dev\entsoe-py\entsoe\parsers.py", line 313, in _parse_price_timeseries
    series.index = _parse_datetimeindex(soup)
  File "C:\Users\user\AppData\Local\Continuum\miniconda3\envs\entsoe-py\lib\site-packages\pandas\core\generic.py", line 5143, in __setattr__
    return object.__setattr__(self, name, value)
  File "pandas\_libs\properties.pyx", line 66, in pandas._libs.properties.AxisProperty.__set__
  File "C:\Users\user\AppData\Local\Continuum\miniconda3\envs\entsoe-py\lib\site-packages\pandas\core\series.py", line 424, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "C:\Users\user\AppData\Local\Continuum\miniconda3\envs\entsoe-py\lib\site-packages\pandas\core\internals\managers.py", line 226, in set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 24 elements, new values have 1 elements
```

My guess is that https://github.com/EnergieID/entsoe-py/blob/5d176699472744c1acef546410826da6549112cf/entsoe/parsers.py#L449 finds the first end tag `<end>2018-01-01T01:00Z</end>` in `soup` when it should really find the last one, i.e. `<end>2018-01-02T00:00Z</end>` so it ends up with a TimeIndex of length 1 (one hour) and fails with the above error.

I tried the above code with `country_code = "BE"` as this is also what the tests cover and in that case the response contains only one `end` tag. I am now wondering why the returned XML looks different for `"BE"` and `"IE-SEM"`? Should we handle the XML differently or can we just say we pick the last `end` tag in which case a fix might be minimal, trivial and would work for both cases.

**Comment by fleimgruber** [comment]
Created matching PR in https://github.com/EnergieID/entsoe-py/pull/72.
