### ISSUE TITLE
Error when running query_scheduled_exchanges for AT-HU Total Commercial Schedules

### ISSUE THREAD

**Issue by mjak009** [EnergieID/entsoe-py#90]
Hi,

I'm using query_scheduled_exchanges to download the Total Commercial Schedules between pairs of BiddingZones. For most pairs it works OK, but for the Austria-Hungary exchange (AT_HU, and the opposite direction), I'm getting an error:

ValueError: Length mismatch: Expected axis has 24 elements, new values have 93 elements

When I accessed data for this pair through the https://transparency.entsoe.eu/ web interface, I noticed the data is given in 15minutes intervals, so maybe this error is connected with this representation. However, for some other pairs with 15 minutes data, like DE-LU_BE, query_scheduled_exchanges works fine.

I run the entsoe-py on WinPython (WPy64-4741) with Pandas 1.1.5.

Any help to resolve that issue will be much appreciated.

Code to reproduce the error:

```
from entsoe import EntsoePandasClient
import pandas as pd

client = EntsoePandasClient(api_key="xxx")

start = pd.Timestamp('20201101', tz='UTC')
end = pd.Timestamp('20201102', tz='UTC')

totATHU = client.query_scheduled_exchanges('AT', 'HU', start=start, end=end)
```

Error:

```
Traceback (most recent call last):
  File "E:/dev/energy/code/mCEP_TP/tp_data/issue.py", line 9, in <module>
    trATHU = client.query_scheduled_exchanges('AT', 'HU', start=start, end=end)
  File "E:\dev\WPy64-3741\python-3.7.4.amd64\lib\site-packages\entsoe\entsoe.py", line 828, in year_wrapper
    frame = func(*args, start=_start, end=_end, **kwargs)
  File "E:\dev\WPy64-3741\python-3.7.4.amd64\lib\site-packages\entsoe\entsoe.py", line 1133, in query_scheduled_exchanges
    ts = parse_crossborder_flows(text)
  File "E:\dev\WPy64-3741\python-3.7.4.amd64\lib\site-packages\entsoe\parsers.py", line 183, in parse_crossborder_flows
    series = series.append(_parse_crossborder_flows_timeseries(soup))
  File "E:\dev\WPy64-3741\python-3.7.4.amd64\lib\site-packages\entsoe\parsers.py", line 521, in _parse_crossborder_flows_timeseries
    series.index = _parse_datetimeindex(soup)
  File "E:\dev\WPy64-3741\python-3.7.4.amd64\lib\site-packages\pandas\core\generic.py", line 5154, in __setattr__
    return object.__setattr__(self, name, value)
  File "pandas\_libs\properties.pyx", line 66, in pandas._libs.properties.AxisProperty.__set__
  File "E:\dev\WPy64-3741\python-3.7.4.amd64\lib\site-packages\pandas\core\series.py", line 424, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "E:\dev\WPy64-3741\python-3.7.4.amd64\lib\site-packages\pandas\core\internals\managers.py", line 227, in set_axis
    f"Length mismatch: Expected axis has {old_len} elements, new "
ValueError: Length mismatch: Expected axis has 24 elements, new values have 93 elements
```

**Comment by kornerc** [comment]
Hi,

I had the same problem with the physical cross border flows between Austria and Hungary.
The source of the error was located in the xml provided from ENTSO-E which contains the data to the query.

I contacted them and they have solved the problem.
Now I can successfully run your code snippet; can you please try if it also works for you?

**Comment by mjak009** [comment]
Hi,

yes, I confirm that it works now.

Thank you very much!

**Comment by birnbaum** [comment]
Hi!

I'm experiencing the same problem for

```python
client.query_crossborder_flows("BE", "GB", start=pd.Timestamp("2020-10-30 00:00:00"), end=pd.Timestamp("2020-11-01 00:00:00"))
```

Error:
```
Traceback (most recent call last):
  File "[...]/site-packages/IPython/core/interactiveshell.py", line 3386, in run_code
    async def run_code(self, code_obj, result=None, *, async_=False):
  File "<ipython-input-1-83b35725c048>", line 1, in <module>
    client.query_crossborder_flows("BE", "GB", start=pd.Timestamp("2020-10-30 00:00:00"), end=pd.Timestamp("2020-11-01 00:00:00"))
  File "[...]/site-packages/entsoe/entsoe.py", line 822, in year_wrapper
    @wraps(func)
  File "[...]/site-packages/entsoe/entsoe.py", line 1076, in query_crossborder_flows
    @year_limited
  File "[...]/site-packages/entsoe/parsers.py", line 171, in parse_crossborder_flows
    def parse_crossborder_flows(xml_text):
  File "[...]/site-packages/entsoe/parsers.py", line 503, in _parse_crossborder_flows_timeseries
    def _parse_crossborder_flows_timeseries(soup):
  File "[...]/site-packages/pandas/core/generic.py", line 5464, in __setattr__
    def __setattr__(self, name: str, value) -> None:
  File "pandas/_libs/properties.pyx", line 66, in pandas._libs.properties.AxisProperty.__set__
  File "[...]/site-packages/pandas/core/series.py", line 437, in _set_axis
    def _set_axis(self, axis: int, labels, fastpath: bool = False) -> None:
  File "[...]/site-packages/pandas/core/internals/managers.py", line 214, in set_axis
    def set_axis(self, axis: int, new_labels: Index) -> None:
ValueError: Length mismatch: Expected axis has 93 elements, new values have 24 elements
```

Is there anything I can do to fix this? The problem only occurs on queries that include this specific time range.

**Comment by quintinnicolas** [comment]
Hi,
It seems to be a similar problem as the one mentioned in #97, the issue occurs when duplicates are found in the xml returned by ENTSOE. A simple workaround is proposed in commit #101.

**Comment by birnbaum** [comment]
Ah I see, thanks for the quick reply :) I'll let you know if the fix works once the PR is merged!
